name: CI test

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: flake8 . --exclude .git,__pycache__,logistic/migtations,manage.py,.venv,venv,admin.py:F401 --max-line-length=120
      - name: Test with pytest
        run: pytest

  build:
    runs-on: ubutu-latest
    needs: tests
    steps:
      - name: Chekout
        uses: actions/checkout@v2

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build the Docker image
        run: docker build -t web:latest .

      - name: Push the Docker container to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run:
          heroku container:push web --app ${{ secrets. HEROKU_APP_NAME }}
          heroku container:release web --app ${{ secrets. HEROKU_APP_NAME }}
          heroku ps:scale web=1 -a ${{ secrets. HEROKU_APP_NAME }}
